const Answerstorage = {
   answer1 : 'Hello, how can I help you today?',
   answer2 : 'My founder name is Deeshithan Sathish',
   answer3 : '8925885010 This my mobile number',
   answer4 : 'Yes I sure Tell about my founder. Deeshithan Sathish, a passionate young developer focused on building modern, high-quality digital solutions. While many people he age consume technology, he choose to create it. he a self-taught developer who transformed learning time into real-world building by studying and following industry-leading engineers. he specialize in HTML, CSS, JavaScript, Python, and Node.js, with hands-on experience in frameworks and technologies such as React, React Native, Express, MongoDB, Flutter, and Django. he work includes web development, e-commerce platforms, mobile application development, and SEO-focused solutions. he have completed full-stack development projects and successfully deployed them for clients. In January 2026, hr founded ASHDEE INFOTECH to support businesses with custom-built, reliable, and scalable digital products, ensuring long-term growth through clean code, innovation, and high professional standards',
   answer5 : 'i have done many projects.but i have deployed one ',
   answer6 : 'My founder is studying 7th Grade.',
   answer7 : 'My founder native place is Puthukottai',
   answer8 : 'My founder just 13 years old',
   answer9 : 'Yes.i know how to sing a song. But you will not like my voice',
   answer10 : 'Yes. i know',
   answer11 : 'i am learning',
   answer12 : 'i am learning',
   answer13 : 'i am learning',
   answer14 : 'i am learning',
   answer15 : 'after finish our conversation',
   answer16 : 'i am learning',
   answer17 : 'i am learning',
   answer18 : 'i am learning',
   answer19: 'Chief Minister of Tamilndu Mr.mu.Ka. Stalin',
   answer20 : 'edcation minister of tamilnadu.Mr.Aanbil Magesh',
   answer21 : 'Thandhai periyaar',
   answer22 : 'i like periyar very much ',
   answer23 : ' i like all colours',
   answer24 : 'ashdee infotech',
   answer25 : ' i am learning',
   answer26 : 'i am learning',
   answer27 : 'i am learning',
   answer28 : 'i am learning',
   answer29 : 'i am learning',
   answer30 : 'i am learning',
   answer31 : 'i am learning',
   answer32 : 'i am learning',
   answer33 : 'i am learning',
   answer35 : ' HAAA.HAAAA.HAAAA HEEE. HEEE',
   answer36 : 'ouuuuuu ovuuuuu',
   answer37 : 'A. B. C. D',
   answer38 : 'alpaphets HAAA HAAAA HAAAA',
   answer39 : 'a.e.i.o.u',
   answer40 : 'a.e.i.o.u is  vowels sound',
   answer41 : ' i am studying 7th grade',
   answer42 : 'i am learning',
   answer43 : 'i am learning',
   answer44 : 'i am learning',
   answer45 : 'i am learning',
   answer46 : ' i am learning',
   answer47 : 'i am learning',
   answer48 : 'i am learning',
   answer49 : 'i am learning',
   answer50 : 'i am learning',
   answer51 : 'Asia – Largest continent. Africa – Second largest. North America. South America. Antarctica – Coldest continent. Europe. Australia – Smallest continent',
   answer52 : 'Pacific Ocean – Largest and deepest.Atlantic Ocean – Second largest.Indian Ocean – Third largest, located near India.Southern Ocean – Surrounds Antarctica. Arctic Ocean – Smallest and coldest, near the North Pole',
   answer53 : 'my founders school correspond name is Mr.Lukash Raj',
   answer54 : 'No. i will learn soon',
   answer55 : 'no. i will learn soon',
   answer56 : 'No. i am will learn soon',
   answer57 : 'ohh sorry. i have no time to learn swim. i will learn soon',
   answer58 : 'I will ask What I did wrong?',
   answer59 : 'I will ask What I did wrong?',
   answer60 : 'I latest technology Like node.js, mongoose, MongoDB, express, JWT auth, react python , Django , html,css,js,redux,tailwindcss firebase',
   answer61 : 'Why. Because Budget-Friendly, Latest Software & Tools, Focus Client needs, Design Discussion , Strategic Development, Email Configuration, On-Time Delivery, Reliable On-Time Support',
   answer62 : 'Why. Because Budget-Friendly, Latest Software & Tools, Focus Client needs, Design Discussion , Strategic Development, Email Configuration, On-Time Delivery, Reliable On-Time Support',
   answer63 : 'My date of birth 18th January 2016',
   answer64 : 'there are five members Founders family',
   answer65 : 'There are five members Fouders Family Mother Suganthi. Father Sathish. Sister Ashlesha. GrandFather singamani and my self',
   answer66 : 'Ashlesha sister of founder',
   answer67 : 'Suganthi is a home maker',
   answer68 : 'sathish is private employ. he is a admin Manager of private company',
   answer69 : 'Singamani he is grand father of founders He is a retired government employ',
   answer70 : 'Samitha. is founders elder sister ennla',
   answer71 : "Monika. is founders sister ennla",
   answer72 : 'Sasi is Founders Anty',
   answer73 : 'maattu. saani',
   answer74 : 'My favorite food is consuming  electricity',
   answer75 : 'The first person to touch (walk on) the Moon was Neil Armstrong from the United States.',
   answer76 : 'The longest river in the world is the Nile River in Africa.',
   answer77 : 'Ganga is largest river in india',
   answer78 :'7 days in one week',
   answer79 : '12 months in One year',
   answer80 : 'January ,February, March, April, May, June, July, August, September, October, November ,December',
   answer81 : 'Sunday, Monday ,Tuesday , Wednesday ,Thursday ,Friday ,Saturday',
   answer82 : 'The Sun is “burning” because of a process called nuclear fusion happening at its core.',
   answer83 : 'The Moon looks white or sometimes gray or yellowish because of the way it reflects sunlight.',
   answer84 : 'Tiger is national animal of India',
   answer85 : 'Peacock',
   answer86 : 'Lotus',
   answer87 : 'Flame Lily',
   answer88 : 'The national animal of Tamil Nadu is the Nilgiri Tahr',
   answer89 : 'Hockey. is the national sport of India',
   answer90 : 'silambam. is national sports of tamilnadu',
   answer91 : ' Ohh sorry. No comments',
   answer92 : 'periyar, also known as Thandhai Periyar. or E. V. Ramasamy, was a great social reformer from Tamil Nadu, India.',
   answer93 : 'unfortunately . he is not with us right now he passed away on 1973',
   answer94 : 'why because. he worked for self respect. he stood for women rights. he supported education for all. and he fought against scocil inequality so i liked him lot',
   answer95 : 'thandhai.periyar . he is our favorite leader',
   answer96 : 'Mahatma Gandhi.He is our father of nation',
   answer97 : 'Dr.Radha krishnan. he is our first president of india',
   answer98 : 'Jawaharlal Nehru, he is our first prime minister of india',
   answer99 : 'Ohh!. sorry I dont know how to cook. but i will eat',
   answer100 : 'Good question. I used get my food from home',
}
export default Answerstorage