const storage = {
   quiz1 : 'hello',
   quiz2 : 'what is your founder name',
   quiz3 : 'what is your mobile number',
   quiz4 : 'can you please tell me about your founder',
   quiz5 : 'how many project you have done till now ?',
   quiz6 : 'what your founder is doing',
   quiz7 : 'what is your founder native place',
   quiz8 : 'what is your founder age',
   quiz9 : 'do you know how to sing a song',
   quiz10 : ' can you please sing a song',
   quiz11: 'do you know tamil songs',
   quiz12 : 'do you know jokes',
   quiz13 : 'please tell me one jokes',
   quiz14 : 'what is ashthi infotech',
   quiz15 : 'when you will go to sleep',
   quiz16 : 'do you know fight with others',
   quiz17 : 'who is president of india now',
   quiz18 : 'who is prime minister of india now',
   quiz19 : 'who is chief minister of tamilnadu',
   quiz20 : 'who is education minister of tamilnadu',
   quiz21 : 'who is your favourite hero',
   quiz22 : 'why',
   quiz23 : 'which colour you like',
   quiz24 : 'what is your nickname',
   quiz25 : 'few names of the wild animal',
   quiz26 : 'few names of the pet animal',
   quiz27 : 'which is the biggest country in the world',
   quiz28 : 'what is the richest country in the world',
   quiz29 : 'what is the poover country in the world',
   quiz30 : 'can you please tell me about tamilnadu',
   quiz31 : 'can you please tell me about chennai',
   quiz32 : 'sing one more song',
   quiz33 : 'tell me one more joke',
   quiz34 : 'do you know how to laugh',
   quiz35 : 'laugh',
   quiz36 : 'cry',
   quiz37 : 'tell me abcd',
   quiz38 : 'tell me alpaphets',
   quiz39 : 'vowels ',
   quiz40 : 'what is a e i o u',
   quiz41 : 'which class are you studying',
   quiz42 : 'do yo know how to drive a car',
   quiz43 : 'flight',
   quiz44 : 'train',
   quiz45 : 'ship',
   quiz46 : 'how baby will cry',
   quiz47 : 'how baby will laugh',
   quiz48 : 'where is your founder studying',
   quiz49 : 'name of the planets',
   quiz50 : 'name of the colour',
   quiz51 : 'name of the continents',
   quiz52 : 'name of the oceans',
   quiz53 : 'what is your school correspond name',
   quiz54 : 'do you know devotional song',
   quiz55 : 'do you know how to fly',
   quiz56 : 'do you know swim',
   quiz57 : 'why you are not learning swim ',
   quiz58 : 'if i kick you what you will do',
   quiz59 : 'if i slap you what you will do',
   quiz60 : 'what are all technologies do you have with you',
   quiz61 : 'why i need to choose ashdee infotech',
   quiz62 : 'why i want to choose ashdee inotech',
   quiz63 : 'what is your date of birth',
   quiz64 : 'how many members in your family',
   quiz65 : 'name of your family members',
   quiz66 : 'who is ashlesha',
   quiz67 : 'who is suganthi',
   quiz68 : 'who is satish',
   quiz69 : 'who is singamani',
   quiz70 : 'who is samitha',
   quiz71 : 'who is monika',
   quiz72 : 'who is sasi',
   quiz73 : 'what samitha like',
   quiz74 : 'what is your favorite food',
   quiz75 : 'who was touch the moon first',
   quiz76 : 'which is the longest river in the world',
   quiz77: 'which is the longest river in india',
   quiz78 : 'how many days are there in a week',
   qui79 : 'how many months are there in a year',
   quiz80 : 'name of the months',
   quiz81 : 'name of the days',
   quiz82 : 'why sun is burning',
   quiz83 : 'why moon is white',
   quiz84 : 'what is the national animal of india',
   quiz85 : 'what is the national bird of india',
   quiz86 : 'what is the nbational flower of india',
   quiz87 : 'what is the national flower of tamilnadu',
   quiz88 : 'what is the national animal of tamilnadu',
   quiz89 : 'what is the national sports of india',
   quiz90 : 'what is the national sports of tamilnadu',
   quiz91 : 'who will win the tamilnadu election',
   quiz92 : 'who is periyaar',
   quiz93 : 'where thandhai periyar is right now',
   quiz94 : 'why do you like periyaar',
   quiz95 : 'who is your favorite leader',
   quiz96 : 'who is father of our nation',
   quiz97 : 'who was first president of india',
   quiz98 : 'who was first prime minister of india ',
   quiz99 : 'do you know cook',
   quiz100 : 'where i can get my food',
}

export default storage